# Generated by Django 6.0.1 on 2026-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID платежа в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачено"),
                    ("failed", "Ошибка оплаты"),
                    ("canceled", "Отменено"),
                ],
                default="pending",
                max_length=50,
                null=True,
                verbose_name="Статус оплаты Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии в Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
